### ISSUE TITLE
pydantic issue

### ISSUE THREAD

**Issue by Ernelene** [seewindcn/reflex-antd#6]
Hi what version of pydantic are you using? 
I am getting this error on reflex_antd/base.py", line 816:
```
_custom_components: Set[CustomComponent] = pydantic.PrivateAttr(default_factory=set)
                                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pydantic.v1.main' has no attribute 'PrivateAttr'
```

**Comment by seewindcn** [comment]
Thank's for report, I am using pydantic 2.7.3.
what's your version of pydantic?

**Comment by Ernelene** [comment]
Thanks for the quick response. I am using the newest v2.8.2

**Comment by Ernelene** [comment]
thank you for the quick response I upgraded to your version of pydantic I get this error now: 
`class<<AntdConfigProvider/>>, args=(), kw={'children': [], 'theme': BaseVar(_var_name='theme.styles.global.body.antd', _var_type=<class 'str'>, _var_is_local=False, _var_is_string=False, _var_full_name_needs_state_prefix=False, 
_var_data=None)}, error: Invalid var passed for prop ConfigProvider.theme, expected type typing.Union[reflex_antd.base.ContainVar, typing.Dict], got value theme.styles.global.body.antd of type <class 'str'>.
Traceback (most recent call last):
  File "...reflex_frontend/.venv/bin/reflex", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/typer/main.py", line 326, in __call__
    raise e
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/typer/main.py", line 309, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/typer/core.py", line 723, in main
    return _main(
           ^^^^^^
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/typer/core.py", line 193, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/typer/main.py", line 692, in wrapper
    return callback(**use_params)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/reflex/reflex.py", line 260, in run
    _run(env, frontend, backend, frontend_port, backend_port, backend_host, loglevel)
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/reflex/reflex.py", line 186, in _run
    prerequisites.get_compiled_app()
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/reflex/utils/prerequisites.py", line 293, in get_compiled_app
    app._compile(export=export)
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/reflex/app.py", line 811, in _compile
    app_wrappers.update(component._get_all_app_wrap_components())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/reflex/components/component.py", line 1641, in _get_all_app_wrap_components
    components.update(child._get_all_app_wrap_components())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/reflex/components/component.py", line 1641, in _get_all_app_wrap_components
    components.update(child._get_all_app_wrap_components())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/reflex/components/component.py", line 1641, in _get_all_app_wrap_components
    components.update(child._get_all_app_wrap_components())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 17 more times]
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/reflex/components/component.py", line 1631, in _get_all_app_wrap_components
    components = self._get_app_wrap_components()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/reflex_antd/base.py", line 995, in _get_app_wrap_components
    (40, "AntdProvider"): _config_provider if _config_provider is not None else config_provider(),
                                                                                ^^^^^^^^^^^^^^^^^
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/reflex_antd/antd/base.py", line 94, in create
    return super().create(
           ^^^^^^^^^^^^^^^
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/reflex/components/component.py", line 811, in create
    return cls(children=children, **props)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/reflex_antd/base.py", line 832, in __init__
    super().__init__(*args, **kw)
  File "...reflex_frontend/.venv/lib/python3.12/site-packages/reflex/components/component.py", line 447, in __init__
    raise TypeError(
TypeError: Invalid var passed for prop ConfigProvider.theme, expected type typing.Union[reflex_antd.base.ContainVar, typing.Dict], got value theme.styles.global.body.antd of type <class 'str'>.`

**Comment by seewindcn** [comment]
fix; my false; ConfigProvider has some nouse codes make this error when theme no set

**Comment by Ernelene** [comment]
Thanks 
Will be on the look out for the update in the pip packages

**Comment by seewindcn** [comment]
done
